### ISSUE TITLE
Is this tool abandonware?

### ISSUE THREAD

**Issue by sleaze** [fzipp/gocyclo#17]
There are unmerged PR's open for nearly half a year.  Is this still being supported or should it be forked to someone who is able to maintain it?

**Comment by gm42** [comment]
I found the same issue and decided to start maintaining a fork here:
* https://github.com/gm42/gocyclo

**Comment by ryan0x44** [comment]
gometalinter is using https://github.com/alecthomas/gocyclo by @alecthomas because PR #1 hasn't been merged

**Comment by gm42** [comment]
@ryan0x44 what do you estimate is the impact of (the lack of) #12? I am not academically versed on the topic but I thought it's quite big, thus decided to make that fork.

**Comment by ryan0x44** [comment]
@gm42 that PR seems pretty dense (lots of "cosmetic" changes in addition to logic changes) and the description doesn't actually describe the change, so I find it hard to estimate. Did you perform and comparisons in output with and without the changes?

**Comment by gm42** [comment]
@ryan0x44 I do not see the bulk of cosmetic changes (maybe we just have a different threshold to judge), but what I noticed is the replacement of the AST/parser with SSA, and the new formula of course.

I did a comparison, and the calculated complexity was smaller on average for the code I checked it on; I picked it because I understood that current gocyclo uses an arbitrary formula rather than the correct one.

@nodirt care to comment?

**Comment by nodirt** [comment]
I think we should be discussing the problems with #12 in #12. I've addressed the concerns in the PR and explained why I believe that the current implementation is incorrect.

**Comment by gm42** [comment]
After the discussion in #12 I have retracted the PR #12 from my fork; it still would be nice for the tool to be actively maintained.

**Comment by ghostsquad** [comment]
any word on whether or not this tool or the fork are abandoned?

**Comment by opencloudengineer** [comment]
I see some activity on the repo recently. 

Even though there has been a lot of activity `(code push)` on this repo since this issue was created, and that's why @fzipp can you please once, confirm here on this issue if this project has been abandoned, and if not then please close this issue.

I'd love to raise an issue and create PR for it.

PS: Thank You @fzipp for the tool, this has been and still is really helpful for me in my Golang learning and development process. 🙏

**Comment by fzipp** [comment]
Hi @opencloudengineer,

thank you for your interest. The project was dormant for a while, but it's not dead. I keep the status quo up-to-date with developments in the Go ecosystem like modules and the upcoming type parameters, and I have reviewed and accepted some improvements since this issue was created, although one PR is still open. So I probably will close this issue.

> I'd love to raise an issue and create PR for it.

If it's a feature request and not just a bug fix, please create an issue before implementing and submitting a PR, so that I and potentially others can weigh in on wether it's in the scope of the project before you do the work, so that your effort is not wasted (unless you need it anyway in a personal fork).
